# tests/generate_tests_inl.py

import os
import re
import sys

def camel_extract_name(name):
    return re.sub(r'Tests\.cpp$', '', name)
    
def camel_to_snake_upper(name):
    name = camel_extract_name(name)
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    s2 = re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1)
    return s2.upper()

def str_to_bool(value):
    if isinstance(value, bool):
        return value
    
    if value.lower() in ('0', 'off', 'no', 'false', 'n', 'ignore', '', 'notfound'):
        return False
        
    return True

def main():
    if len(sys.argv) < 3:
        return

    vtf_as_dll = sys.argv[1]
    output_dir = sys.argv[2]
    input_files = sys.argv[3:]

    enum_entries = []
    for file_name in input_files:
        if file_name == "allTests.cpp" or not file_name.endswith("Tests.cpp"):
            continue
        expected_hpp = camel_extract_name(file_name) + 'Tests.hpp'
        if expected_hpp not in input_files:
            print("[generate_tests_inl.py] Skip: ", file_name)
            continue
        enum_entries.append(camel_to_snake_upper(file_name))

    enum_entries.sort()

    #print(enum_entries)

    new_content = """// allTests.inl
// Autogenerated file by generate_tests_inl.py
// Do not modify this file manually

enum TestIdentifier {
"""
    for entry in enum_entries:
        new_content += f"    {entry},\n"

    if str_to_bool(vtf_as_dll):
        new_content += "    VTF_LAUNCHER,\n"

    new_content += "};\n"

    output_path = os.path.join(output_dir, "allTests.inl")

    current_content = ""
    if os.path.exists(output_path):
        with open(output_path, "r", encoding="utf-8") as current_file:
            current_content = current_file.read()
        
    if current_content != new_content:
       with open(output_path, "w", encoding="utf-8") as inl_file:
           inl_file.write(new_content)
       print(f"[generate_test_inl.py] Updated {output_path}")

if __name__ == "__main__":
    main()

