#version 460 core
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_opacity_micromap : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, std430) buffer RayOrigins {
	vec4 values[];
} origins;
layout(set = 0, binding = 2, std430) buffer OutputModes {
	uint values[];
} modes;

layout(location = 0) rayPayloadEXT uint value;

void main()
{
	const uint  idx       = gl_LaunchIDEXT.x;
	const vec3  origin    = origins.values[idx].xyz;
	const vec3  direction = vec3(0.0, 0.0, -1.0);
	const float tMin      = 0.0;
	const float tMax      = 2.0;

	value = 0xFFFFFFFFu;
	traceRayEXT(topLevelAS, gl_RayFlagsNoneEXT, 0xFFu, 0u, 0u, 0u, origin, tMin, direction, tMax, 0);
	modes.values[idx] = value;
}
