#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) buffer Buffer { uint data[]; };
layout(push_constant) uniform PC { uvec2 v; };

void main()
{
    data[0] = v.x + 1u;
    data[1] = v.y + 1u;
    uint x = v.x;
    while (x > v.y)
    {
        x = x + 1;
        if (x == 1048576)
        {
            x = v.x;
        }
    }
    data[2] = data[2] + 1u;
    data[3] = uint(x);
}
