#version 450
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;
struct Item {
    uint value;
    uint pad[4];
};
layout(binding = 0) buffer Items { Item items[]; } items;
void main()
{
    uint i = (gl_WorkGroupID.z * gl_NumWorkGroups.y * gl_NumWorkGroups.x +
                                   gl_WorkGroupID.y * gl_NumWorkGroups.x +
                                                        gl_WorkGroupID.x)
            * gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z + gl_LocalInvocationIndex;
    items.items[i].value = i + 1;
}

