
if ("${GLFW3_LIB_PATH}" STREQUAL "")
	if (NOT "${LOOK_FOR_GLFW3}" STREQUAL "")
		get_filename_component(ABS_LOOK_FOR_GLFW3 ${LOOK_FOR_GLFW3} REALPATH)
		find_glfw3( "${ABS_LOOK_FOR_GLFW3}"  "${HINT_FOR_GLFW3}" Q_GLFW3_INCLUDE_DIR Q_GLFW3_LIB_PATH)
		string(REPLACE "\"" "" GLFW3_LIB_PATH     "${Q_GLFW3_LIB_PATH}")
	endif()
endif()
if ("${GLFW3_INCLUDE_DIR}" STREQUAL "")
	string(REPLACE "\"" "" GLFW3_INCLUDE_DIR  "${Q_GLFW3_INCLUDE_DIR}")
endif()

if("${GLFW3_LIB_PATH}" STREQUAL "")
    if(${SYSTEM_OS_LINUX} EQUAL 0)
        message(WARNING "GLFW3_LIB_PATH not defined, try for an example: c:\\glfw-3.3.6.bin.WIN64\\lib-vc2019\\glfw3.lib")
    else()
        message(WARNING "GLFW3_LIB_PATH not defined, try for an example: /opt/glfw/build/src/libglfw3.a")
    endif()
    message(WARNING "You can also try -DLOOK_FOR_GLFW3 and -DHINT_FOR_GLFW3 if it is ambigous, "
                    "example: -DLOOK_FOR_GLFW2=/c/VulkanDeps/glfw-3.3.8.bin.WIN64/ -HINT_FOR_GLFW3=lib-vc2022")
	message(FATAL_ERROR "Looking for GLFW3 dependencied failed.")
endif()

message(STATUS "Define variable GLFW3_LIB_PATH=${GLFW3_LIB_PATH}")
if("${GLFW3_INCLUDE_DIR}" STREQUAL "")
    if(${SYSTEM_OS_LINUX} EQUAL 0)
		message(WARNING "GLFW3_INCLUDE_DIR not defined, try for an example: c:\\glfw-3.3.6.bin.WIN64\\include")
    else()
		message(WARNING "GLFW3_INCLUDE_DIR not defined, try for an example: /opt/glfw/include")
    endif()
	message(WARNING "You can also try -DLOOK_FOR_GLFW3 and -DHINT_FOR_GLFW3 if it is ambigous, "
		"example: -DLOOK_FOR_GLFW2=/c/VulkanDeps/glfw-3.3.8.bin.WIN64/ -HINT_FOR_GLFW3=lib-vc2022")
	message(FATAL_ERROR "Looking for GLFW3 dependencied failed.")
endif()
message(STATUS "Define variable GLFW3_INCLUDE_DIR=${GLFW3_INCLUDE_DIR}")
